{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-iamf",
    "version": "1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.1.aar",
          "url": "media3-decoder-iamf-1.11.1.aar",
          "size": 12004693,
          "sha512": "5a61d5d740e2f88444c758f5b765d077b31471e3600bd31111998932d6d8d69313f42964cb53e8bb34336bb39bddb90661c3575a817aad266bd46d9316279412",
          "sha256": "73cd2df3f3bfc95e8f6c34df5cd9a4946ecf7ab22f24fd015ba1a65090636810",
          "sha1": "6a15c867c273bf4e14e809bc092c7806ee6a2eff",
          "md5": "a396cc0e96e163c5ec1f101a34c318a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.1.aar",
          "url": "media3-decoder-iamf-1.11.1.aar",
          "size": 12004693,
          "sha512": "5a61d5d740e2f88444c758f5b765d077b31471e3600bd31111998932d6d8d69313f42964cb53e8bb34336bb39bddb90661c3575a817aad266bd46d9316279412",
          "sha256": "73cd2df3f3bfc95e8f6c34df5cd9a4946ecf7ab22f24fd015ba1a65090636810",
          "sha1": "6a15c867c273bf4e14e809bc092c7806ee6a2eff",
          "md5": "a396cc0e96e163c5ec1f101a34c318a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.1-sources.jar",
          "url": "media3-decoder-iamf-1.11.1-sources.jar",
          "size": 10758,
          "sha512": "bf4053afe46ac7845d77d22320a36467b52c662399257f8915f20e94cebd8349897d14ce5e04e56107c0238f046d01d2fcf418185ea6ead35c5e6598024a9cd4",
          "sha256": "cf31c3a765727b532bc2c39a2a0cc76f41c97cef233e220cddef602071d5c269",
          "sha1": "4771b9824ec8370593991b2405539d2cb669df8d",
          "md5": "309a4e033b9bc384fab0cc46f3364800"
        }
      ]
    }
  ]
}
