{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-iamf",
    "version": "1.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-iamf-1.10.1.aar",
          "url": "media3-decode-iamf-1.10.1.aar",
          "size": 11759569,
          "sha512": "34e9dd32beefac6200f71b9bfe8a3f3949008bc251b38db2462af1217ca5119b9de865756bd26adfe76d1db0863979047cec705219b2bfafeeb9d9811e1a5646",
          "sha256": "7283fbd9d57ea8f97d3944b53e11bde350f8605d1372f06a5855ea8be9d3ad85",
          "sha1": "2047503ad357152c7789004fef9d75baa4da7295",
          "md5": "f8f68486d500537f541bf18c0623f627"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-iamf-1.10.1.aar",
          "url": "media3-decode-iamf-1.10.1.aar",
          "size": 11759569,
          "sha512": "34e9dd32beefac6200f71b9bfe8a3f3949008bc251b38db2462af1217ca5119b9de865756bd26adfe76d1db0863979047cec705219b2bfafeeb9d9811e1a5646",
          "sha256": "7283fbd9d57ea8f97d3944b53e11bde350f8605d1372f06a5855ea8be9d3ad85",
          "sha1": "2047503ad357152c7789004fef9d75baa4da7295",
          "md5": "f8f68486d500537f541bf18c0623f627"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-iamf-1.10.1-sources.jar",
          "url": "media3-decode-iamf-1.10.1-sources.jar",
          "size": 10272,
          "sha512": "87a2f249be87db69ea205f7ade2ae7679b7692a30e9dd0b502d5469c124de88bb3c0a68d815b449bd8af36cf945817be13fdc41c891725e3ee93906754346002",
          "sha256": "cdb22503a1506ae59b5d17f6129b08f42aa5085127b02c25d09ea264e57ad47e",
          "sha1": "634607c02ce0bfba6543a372dc6584b516cf4ab4",
          "md5": "539132c136a87cb5c9df6255e8309116"
        }
      ]
    }
  ]
}
