{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.7.1.aar",
          "url": "media3-exoplayer-1.7.1.aar",
          "size": 1524540,
          "sha512": "024d7fcc46b96255fac02bd891ee15dda1b7748e4d2ec08c42145c800afe7b6fdde5bd9f392437fe6a9d5d34ccad8066e9dc435fd130b6c6b0da8ccef05ab71f",
          "sha256": "902c2e2f215d5927969bf87cf1aeb17ff9de6fcca18dfb6021ebc2bdec58bc97",
          "sha1": "4d1933f3d216650fb825c7a4414b9c6a8e37b39d",
          "md5": "1e60e1eb9225e28139ae96b0ceada0e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.7.1.aar",
          "url": "media3-exoplayer-1.7.1.aar",
          "size": 1524540,
          "sha512": "024d7fcc46b96255fac02bd891ee15dda1b7748e4d2ec08c42145c800afe7b6fdde5bd9f392437fe6a9d5d34ccad8066e9dc435fd130b6c6b0da8ccef05ab71f",
          "sha256": "902c2e2f215d5927969bf87cf1aeb17ff9de6fcca18dfb6021ebc2bdec58bc97",
          "sha1": "4d1933f3d216650fb825c7a4414b9c6a8e37b39d",
          "md5": "1e60e1eb9225e28139ae96b0ceada0e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.7.1-sources.jar",
          "url": "media3-exoplayer-1.7.1-sources.jar",
          "size": 1104644,
          "sha512": "b2b2bd9cb6164439fe0c5d75222cfbde5626c5d6c4a979c3f45024e35ac31c7d0d2270e4cf9ead60f94c5191f222cab9eee38860de32cf00f4fb7b8d292077a8",
          "sha256": "4b6ffcfec4aa63263087fcaa2976c3bfcd13af0f2f7d83c914a2359480110db7",
          "sha1": "9f73c6f32c9414134357dce7eeca3863b79a910c",
          "md5": "5505629e628f6752276b66314aec7871"
        }
      ]
    }
  ]
}
